# name: SonarCloud
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, synchronize, reopened]
# jobs:
#   sonarcloud:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Set up JDK 17
#         uses: actions/setup-java@v1
#         with:
#           java-version: '17'
#       - name: Cache SonarCloud packages
#         uses: actions/cache@v1
#         with:
#           path: ~/.sonar/cache
#           key: ${{ runner.os }}-sonar
#           restore-keys: ${{ runner.os }}-sonar
#       - name: Install SonarCloud Scanner
#         run: |
#           curl -sL https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip -o build-wrapper-linux-x86.zip
#           unzip build-wrapper-linux-x86.zip -d ~/sonar-scanner
#           export PATH="$PATH:~/sonar-scanner/build-wrapper-linux-x86"
#       - name: SonarCloud Scan
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         run: |
#           sonar-scanner \
#           -Dsonar.organization=alv18051 \
#           -Dsonar.projectKey=alv18051_sonarcloud-analysis \
#           -Dsonar.sources=. \
#           -Dsonar.host.url=https://sonarcloud.io
#perpe

name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud_analysis:
    name: sonarcloud_analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}




